apiVersion: apps/v1
kind: Deployment
metadata:
  name: speckle-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: speckle-frontend
    project: speckle-server
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: speckle-frontend
      project: speckle-server
  template:
    metadata:
      labels:
        app: speckle-frontend
        project: speckle-server
    spec:
      containers:
      - name: main
        image: speckle/speckle-frontend:{{ .Values.docker_image_tag }}
        resources:
          requests: {{ .Values.frontend.requests }}
          limits: {{ .Values.frontend.limits }}

